name: PanjwaniBus
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  archive: ^3.3.0
  autocomplete_textfield: null
  carousel_slider: ^5.0.0
  cloud_firestore: null
  cupertino_icons: null
  firebase_auth: null
  firebase_core: null
  flutter:
    sdk: flutter
  flutter_animated_button: null
  flutter_lints: null
  flutter_localization: null
  flutter_pdfview: null
  flutter_polyline_points: null
  flutter_rating_bar: null
  flutter_share: null
  flutter_spinkit: null
  flutter_widget_from_html_core: null
  fluttertoast: null
  geolocator: null
  get: null
  google_maps_flutter: null
  http: null
  http_auth: null
  image_gallery_saver: null
  intl_phone_field: null
  intl_phone_number_field: null
  location: null
  lottie: null
  onesignal_flutter: null
  otp_text_field: null
  package_info_plus: ^8.1.2
  path_provider: null
  pdf: null
  permission_handler: null
  printing: null
  provider: null
  razorpay_flutter: null
  share_plus: null
  shared_preferences: null
  smooth_page_indicator: null
  syncfusion_flutter_datepicker: null
  table_calendar: null
  url_launcher: null
  webview_flutter: null
  win32: ^5.5.3
dependency_overrides:
      win32: ^5.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/

  fonts:
    - family: SofiaProLight
      fonts:
        - asset: assets/All_Fonts/SofiaProLight.ttf
    - family: SofiaProBold
      fonts:
        - asset: assets/All_Fonts/SofiaProBold.ttf
