// ignore_for_file: file_names

import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_English'   : {
      "Earn":"Earn",
      "for Each":"for Each",
      "Friend you refer":"Friend you refer",
      "You get":"You get",
      "on your wallet":"on your wallet",
      "on their first complete transaction":"on their first complete\ntransaction",
      "Friend get":"Friend get",
      "Personal info":"Personal info",
      "Refer and earn":"Refer and earn",
      "Language":"Language",
      "Faq":"Faq",
      "Dark Mode":"Dark Mode",
      "Dark Node":"Dark Node",
      "ProZigzagBusbus": "ProZigzagBusbus",
      "Your Journey, Your Way": "Your Journey, Your Way",
      "Seamless Travel Simplified": "Seamless Travel Simplified",
      "Book, Ride, Enjoy": "Book, Ride, Enjoy",
      "Explore, One Bus at a Time": "Explore, One Bus at a Time",
      "Customize your travel effortlessly": "Customize your travel effortlessly",
      "Easy booking and boarding for a stress-free journey": "Easy booking and boarding for a stress-free journey",
      "Swift booking and delightful bus rides": "Swift booking and delightful bus rides",
      "Discover new places, one bus ride after another": "Discover new places, one bus ride after another",
      "Welcome To ProZigzagBus": "Welcome To ProZigzagBus",
      "We Will send OTP on this mobile number.": "We Will send OTP on this mobile number.",
      "Phone Number": "Phone Number",
      "Enter Your Password": "Enter Your Password",
      "Enter Vlide Input": "Enter Vlide Input",
      "PROCEED": "PROCEED",
      "Forgot Password ?": "Forgot Password ?",
      "Create Account or Sign in": "Create Account or Sign in",
      "Enter Your Name": "Enter Your Name",
      "Enter Your Email Id": "Enter Your Email Id",
      "GENERATE OTP": "GENERATE OTP",
      "(ONE TIME PASSWORD)": "(ONE TIME PASSWORD)",
      "HAVE A REFERRAL CODE?": "HAVE A REFERRAL CODE?",
      "Don’t Have an account yet? Sign Up": "Don’t Have an account yet? Sign Up",
      "ProZigzagBus": "ProZigzagBus",
      "Date": "Date",
      "Today": "Today",
      "From": "From",
      "Home": "Home",
      "My Ticket": "My Ticket",
      "to": "to",
      "Account": "Account",
      "Faq List": "Faq List",
      "Refer a Friend": "Refer a Friend",
      "Share the referral link with your friends": "Share the referral link with your friends",
      "Logout": "Logout",
      "Yes,Logout": "Yes,Logout",
      "Cancel": "Cancel",
      "Are you sure you want to log out?": "Are you sure you want to log out?",
      "Delete Account": "Delete Account",
      "Yes,Remove": "Yes,Remove",
      "Are you sure you want to delete account?": "Are you sure you want to delete account?",
      "Confirm": "Confirm",
      "Enter Input": "Enter Input",
      "Profile Edit": "Profile Edit",
      "About": "About",
      "General": "General",
      "My Account": "My Account",
      "100": "100",
      "300": "300",
      "500": "500",
      "1000": "1000",
      "1100": "1100",
      "1300": "1300",
      "1500": "1500",
      "1700": "1700",
      "2000": "2000",
      "Top up Amount": "Top up Amount",
      "Top up": "Top up",
      "Your balance": "Your balance",
      "Top Up": "Top Up",
      "Continue": "Continue",
      "Payment Getway Methode": "Payment Getway Methode",
      "CONTINUE": "CONTINUE",
      "Not Valid": "Not Valid",
      "Another Top Up": "Another Top Up",
      "Done For Now": "Done For Now",
      "Successfuly": "Successfuly",
      "Transaction History": "Transaction History",
      "My Wallet": "My Wallet",
      "Image saved in gallery": "Image saved in gallery",
      "Total Price": "Total Price",
      "Wallet": "Wallet",
      "Discount": "Discount",
      "Price": "Price",
      "Price Details": "Price Details",
      "Email": "Email",
      "Full Name": "Full Name",
      "Contact Details": "Contact Details",
      "Seat": "Seat",
      "Age": "Age",
      "Name": "Name",
      "Passenger(S)": "Passenger(S)",
      "Ticket Id": "Ticket Id",
      "Transaction Id": "Transaction Id",
      "Payment Methode": "Payment Methode",
      "Booking Date": "Booking Date",
      "Bus Details": "Bus Details",
      "Completed": "Completed",
      "Rating": "Rating",
      "Enter your Feedback": "Enter your Feedback",
      "Download Ticket": "Download Ticket",
      "You dont`t have any booking records!": "You dont`t have any booking records!",
      "No booking found": "No booking found",
      "Completed Trips": "Completed Trips",
      "Upcoming Trips": "Upcoming Trips",
      "My Tickets": "My Tickets",
      "Tax": "Tax",
      "Pay from Wallet": "Pay from Wallet",
      "Remove": "Remove",
      "Coupon Applied !": "Coupon Applied !",
      "Apply Coupon": "Apply Coupon",
      "Apply": "Apply",
      "Not Apply": "Not Apply",
      "Min Amount": "Min Amount",
      "Valid untill": "Valid untill",
      "Total Pay": "Total Pay",
      "EXTERNAL_WALLET IS": "EXTERNAL_WALLET IS",
      "ERROR HERE": "ERROR HERE",
      "SUCCESS PAYMENT": "SUCCESS PAYMENT",
      "gender": "gender",
      "seat_no": "seat_no",
      "age": "age",
      "name": "name",
      "Back to Home": "Back to Home",
      "View Transaction": "View Transaction",
      "Congratulation! your bus ticket is confirmed. For more details check the My Booking tab.": "Congratulation! your bus ticket is confirmed. For more details check the My Booking tab.",
      "Booking Confirmed!": "Booking Confirmed!",
      "Enter Age": "Enter Age",
      "Enter Full Name": "Enter Full Name",
      "Business Email": "Business Email",
      "Business Address": "Business Address",
      "Business Name": "Business Name",
      "GSTIN": "GSTIN",
      "Enter Mobile Number": "Enter Mobile Number",
      "Enter Email id": "Enter Email id",
      "Email Id": "Email Id",
      "Gender": "Gender",
      "Passenger": "Passenger",
      "Passenger Details": "Passenger Details",
      "Enter Plese Input": "Enter Plese Input",
      "(Exclusive of Taxes)": "(Exclusive of Taxes)",
      "Amount :": "Amount :",
      "Next Step": "Next Step",
      "Plese Select Boarding And Drop Point": "Plese Select Boarding And Drop Point",
      "Droping Point": "Droping Point",
      "Boarding Point": "Boarding Point",
      "Upper Berth": "Upper Berth",
      "Lower Berth": "Lower Berth",
      "passengers to a single booking with this operator": "passengers to a single booking with this operator",
      "You can not add more than": "You can not add more than",
      "Booked by female passenger": "Booked by female passenger",
      "Selected by you": "Selected by you",
      "Booked by Others": "Booked by Others",
      "Available": "Available",
      "Know about seat types": "Know about seat types",
      "Upper Seat": "Upper Seat",
      "Lower Seat": "Lower Seat",
      "Cancellation Policy": "Cancellation Policy",
      "Review": "Review",
      "Amenities": "Amenities",
      "Seats": "Seats",
      "/ Sleeper": "/ Sleeper",
      "ProZigzagBus fulfilled buses are not available at this time.": "ProZigzagBus fulfilled buses are not available at this time.",
      "Change": "Change",
      "No reviews found": "No reviews found",
      "AC Seater": "AC Seater",
      "Special Offer": "Special Offer",
      "Recent Booking": "Recent Booking",
      "Tomorrow": "Tomorrow",
      "not valide": "not valide",
      "Search Buses": "Search Buses",
      "Enter referral code (optional)": "Enter referral code (optional)",
    },
    'en_spanse'    : {
      "Earn":"Ganar",
      "for Each":"para cada",
      "Friend you refer":"Amigo al que refieres",
      "You get": "Usted obtiene",
      "on your wallet": "en tu billetera",
      "on their first complete transaction": "en su primera transacción completa",
      "Friend get": "Amigo consigue",
      "Dark Mode": "Modo oscuro",
      "Personal info": "Información personal",
      "Refer and earn": "Refiere y gana",
      "Language": "Idioma",
      "Faq": "Preguntas más frecuentes",
      "Dark Node": "Nodo oscuro",
      "ProZigzagBusbus": "ProZigzagBus",
      "Your Journey, Your Way": "Tu viaje, a tu manera",
      "Seamless Travel Simplified": "Viajes sin interrupciones simplificados",
      "Book, Ride, Enjoy": "Reserva, viaja, disfruta",
      "Explore, One Bus at a Time": "Explora, un autobús a la vez",
      "Customize your travel effortlessly": "Personaliza tu viaje sin esfuerzo",
      "Easy booking and boarding for a stress-free journey": "Reserva y embarque sencillos para un viaje sin estrés",
      "Swift booking and delightful bus rides": "Reservas rápidas y viajes en autobús encantadores",
      "Discover new places, one bus ride after another": "Descubre nuevos lugares, un viaje en autobús tras otro.",
      "Welcome To ProZigzagBus": "Bienvenido a ProZigzagBusbus",
      "We Will send OTP on this mobile number.": "Enviaremos OTP a este número de móvil.",
      "Phone Number": "Número de teléfono",
      "Enter Your Password": "Ingresa tu contraseña",
      "Enter Vlide Input": "Por favor ingrese entradas válidas",
      "PROCEED": "PROCEDER",
      "Forgot Password ?": "Has olvidado tu contraseña ?",
      "Create Account or Sign in": "Crear cuenta o iniciar sesión",
      "Enter Your Name": "Introduzca su nombre",
      "Enter Your Email Id": "Ingrese su identificación de correo electrónico",
      "GENERATE OTP": "GENERAR OTP",
      "(ONE TIME PASSWORD)": "(CONTRASEÑA DE UN SOLO TIEMPO)",
      "HAVE A REFERRAL CODE?": "¿TIENES UN CÓDIGO DE REFERENCIA?",
      "Don’t Have an account yet? Sign Up": "¿Aún no tienes una cuenta? Inscribirse",
      "ProZigzagBus": "ProZigzagBusbus",
      "Date": "Fecha",
      "Today": "Hoy",
      "From": "De",
      "To": "A",
      "to": "a",
      "Faq List": "Lista de preguntas frecuentes",
      "Refer a Friend": "Recomendar un amigo",
      "Share the referral link with your friends": "Comparte el enlace de referencia con tus amigos.",
      "Logout": "Cerrar sesión",
      "Yes,Logout": "Sí, cerrar sesión",
      "Cancel": "Cancelar",
      "Are you sure you want to log out?": "¿Está seguro de que desea cerrar sesión?",
      "Delete Account": "Borrar cuenta",
      "Yes,Remove": "Sí, eliminar",
      "Are you sure you want to delete account?": "¿Estás seguro de que deseas eliminar la cuenta?",
      "Confirm": "Confirmar",
      "Enter Input": "Ingresar entrada",
      "Profile Edit": "Editar perfil",
      "About": "Acerca de",
      "General": "General",
      "My Account": "Mi cuenta",
      "100": "100",
      "300": "300",
      "500": "500",
      "1000": "1000",
      "1100": "1100",
      "1300": "1300",
      "1500": "1500",
      "1700": "1700",
      "2000": "2000",
      "Top up Amount": "Importe de recarga",
      "Top up": "Completar",
      "Your balance": "Tu balance",
      "Top Up": "Completar",
      "Continue": "Continuar",
      "Payment Getway Methode": "Método de vía de pago",
      "CONTINUE": "CONTINUAR",
      "Not Valid": "Por favor ingrese entradas válidas",
      "Another Top Up": "Otra recarga",
      "Done For Now": "Hecho por ahora",
      "Successfuly": "Con éxito",
      "Transaction History": "Historial de transacciones",
      "My Wallet": "Mi billetera",
      "Image saved in gallery": "Imagen guardada en la galería.",
      "Total Price": "Precio total",
      "Wallet": "Billetera",
      "Discount": "Descuento",
      "Price": "Precio",
      "Price Details": "Detalles del precio",
      "Email": "Correo electrónico",
      "Full Name": "Nombre completo",
      "Contact Details": "Detalles de contacto",
      "Seat": "Asiento",
      "Age": "Edad",
      "Name": "Nombre",
      "Passenger(S)": "Pasajero(s)",
      "Ticket Id": "Identificación de entradas",
      "Transaction Id": "ID de transacción",
      "Payment Methode": "Método de pago",
      "Booking Date": "Fecha para registrarse",
      "Bus Details": "Detalles del autobús",
      "Completed": "Terminado",
      "Rating": "Clasificación",
      "Enter your Feedback": "Ingrese sus comentarios",
      "Download Ticket": "Descargar Entrada",
      "You dont`t have any booking records!": "¡No tienes ningún registro de reserva!",
      "No booking found": "No se encontró ninguna reserva",
      "Completed Trips": "Viajes completados",
      "Upcoming Trips": "Próximos viajes",
      "My Tickets": "Mis entradas",
      "Tax": "Impuesto",
      "Pay from Wallet": "Pagar desde Wallet",
      "Remove": "Eliminar",
      "Coupon Applied !": "¡Cupón aplicado!",
      "Apply Coupon": "Aplicar cupón",
      "Apply": "Aplicar",
      "Not Apply": "No aplicar",
      "Min Amount": "Cantidad mínima",
      "Valid untill": "Válido hasta",
      "Total Pay": "Pago total",
      "EXTERNAL_WALLET IS": "EXTERNAL_WALLET ES",
      "ERROR HERE": "ERROR AQUÍ",
      "SUCCESS PAYMENT": "PAGO EXITOSO",
      "gender": "género",
      "seat_no": "asiento_no",
      "age": "edad",
      "name": "nombre",
      "Back to Home": "De vuelta a casa",
      "View Transaction": "Ver transacción",
      "Congratulation! your bus ticket is confirmed. For more details check the My Booking tab.": "¡Felicitaciones! Su billete de autobús está confirmado. Para obtener más detalles, consulta la pestaña Mi billete.",
      "Booking Confirmed!": "¡Reserva confirmada!",
      "Enter Age": "Ingrese la edad",
      "Enter Full Name": "Ingrese el nombre completo",
      "Business Email": "email de negocios",
      "Business Address": "Dirección de Negocios",
      "Business Name": "Nombre del Negocio",
      "GSTIN": "GSTIN",
      "Enter Mobile Number": "Ingrese el número de móvil",
      "Enter Email id": "Ingrese la identificación de correo electrónico",
      "Email Id": "Identificación de correo",
      "Gender": "Género",
      "Passenger": "Pasajero",
      "Passenger Details": "detalles del pasajero",
      "Enter Plese Input": "Ingrese por favor ingrese",
      "(Exclusive of Taxes)": "(Excluido de Impuestos)",
      "Amount :": "Cantidad :",
      "Next Step": "Próximo paso",
      "Plese Select Boarding And Drop Point": "Por favor seleccione el punto de embarque y desembarque",
      "Droping Point": "Punto de caída",
      "Boarding Point": "Punto de embarque",
      "Upper Berth": "Litera superior",
      "Lower Berth": "Litera baja",
      "passengers to a single booking with this operator": "pasajeros a una única reserva con este operador",
      "You can not add more than": "No puedes agregar más de",
      "Booked by female passenger": "Reservado por pasajera",
      "Selected by you": "Seleccionado por ti",
      "Booked by Others": "Reservado por otros",
      "Available": "Disponible",
      "Know about seat types": "Conozca los tipos de asientos",
      "Upper Seat": "Asiento superior",
      "Lower Seat": "Asiento inferior",
      "Cancellation Policy": "Política de cancelación",
      "Review": "Revisar",
      "Amenities": "Comodidades",
      "Seats": "Asientos",
      "/ Sleeper": "/ Durmiente",
      "ProZigzagBus fulfilled buses are not available at this time.": "Los autobuses con servicio ProZigzagBusbus no están disponibles en este momento.",
      "Change": "Cambiar",
      "No reviews found": "No se encontraron reseñas",
      "AC Seater": "Asientos de aire acondicionado",
      "Special Offer": "Oferta especial",
      "Recent Booking": "Reserva reciente",
      "Tomorrow": "Mañana",
      "not valide": "Por favor ingrese entradas válidas",
      "Search Buses": "Buscar autobuses",
      "Enter referral code (optional)": "Ingrese el código de referencia (opcional)",
      "Home": "Hogar",
      "My Ticket": "Mi billete",
      "Account": "cuentat"
    },
    'ur_arabic'    : {
      "Earn":"يكسب",
      "for Each":"لكل",
      "Friend you refer":"صديق تشير إليه",
      "You get": "لقد حصلت",
      "on your wallet": "على محفظتك",
      "on their first complete transaction": "في أول معاملة كاملة لهم",
      "Friend get": "صديق الحصول على",
      "Dark Mode": "الوضع المظلم",
      "Personal info": "معلومات شخصية",
      "Refer and earn": "الرجوع وكسب",
      "Language": "لغة",
      "Faq": "التعليمات",
      "Dark Node": "العقدة المظلمة",
      "ProZigzagBusbus": "متعرج",
      "Your Journey, Your Way": "رحلتك، طريقك",
      "Seamless Travel Simplified": "السفر السلس والمبسط",
      "Book, Ride, Enjoy": "احجز، اركب، استمتع",
      "Explore, One Bus at a Time": "استكشف، حافلة واحدة في كل مرة",
      "Customize your travel effortlessly": "قم بتخصيص سفرك دون عناء",
      "Easy booking and boarding for a stress-free journey": "سهولة الحجز والصعود لرحلة خالية من التوتر",
      "Swift booking and delightful bus rides": "حجز سريع ورحلات حافلة ممتعة",
      "Discover new places, one bus ride after another": "اكتشف أماكن جديدة، رحلة بالحافلة تلو الأخرى",
      "Welcome To ProZigzagBus": "مرحبا بكم في زيجزاجبوس",
      "We Will send OTP on this mobile number.": "سوف نرسل OTP على رقم الهاتف المحمول هذا.",
      "Phone Number": "رقم التليفون",
      "Enter Your Password": "ادخل رقمك السري",
      "Enter Vlide Input": "الرجاء إدخال مدخلات صالحة",
      "PROCEED": "يتابع",
      "Forgot Password ?": "هل نسيت كلمة السر ؟",
      "Create Account or Sign in": "إنشاء حساب أو تسجيل الدخول",
      "Enter Your Name": "أدخل أسمك",
      "Enter Your Email Id": "أدخل معرف البريد الإلكتروني الخاص بك",
      "GENERATE OTP": "إنشاء كلمة مرور لمرة واحدة",
      "(ONE TIME PASSWORD)": "(كلمة السر لمرة واحدة)",
      "HAVE A REFERRAL CODE?": "هل لديك رمز إحالة؟",
      "Don’t Have an account yet? Sign Up": "لا تملك حسابا حتى الآن؟ اشتراك",
      "ProZigzagBus": "متعرج",
      "Date": "تاريخ",
      "Today": "اليوم",
      "From": "من",
      "To": "ل",
      "to": "ل",
      "Faq List": "قائمة الأسئلة الشائعة",
      "Refer a Friend": "أوص أحد الأصدقاء",
      "Share the referral link with your friends": "شارك رابط الإحالة مع أصدقائك",
      "Logout": "تسجيل خروج",
      "Yes,Logout": "نعم، تسجيل الخروج",
      "Cancel": "يلغي",
      "Are you sure you want to log out?": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
      "Delete Account": "حذف الحساب",
      "Yes,Remove": "نعم، إزالة",
      "Are you sure you want to delete account?": "هل أنت متأكد أنك تريد حذف الحساب؟",
      "Confirm": "يتأكد",
      "Enter Input": "أدخل الإدخال",
      "Profile Edit": "تعديل الملف الشخصي",
      "About": "عن",
      "General": "عام",
      "My Account": "حسابي",
      "100": "100",
      "300": "300",
      "500": "500",
      "1000": "1000",
      "1100": "1100",
      "1300": "1300",
      "1500": "1500",
      "1700": "1700",
      "2000": "2000",
      "Top up Amount": "تعبئة المبلغ",
      "Top up": "فوق حتى",
      "Your balance": "رصيدك",
      "Top Up": "فوق حتى",
      "Continue": "يكمل",
      "Payment Getway Methode": "طريقة بوابة الدفع",
      "CONTINUE": "يكمل",
      "Not Valid": "الرجاء إدخال مدخلات صالحة",
      "Another Top Up": "تعبئة أخرى",
      "Done For Now": "تم الآن",
      "Successfuly": "بنجاح",
      "Transaction History": "تاريخ المعاملات",
      "My Wallet": "محفظتى",
      "Image saved in gallery": "الصورة المحفوظة في المعرض",
      "Total Price": "السعر الكلي",
      "Wallet": "محفظة",
      "Discount": "تخفيض",
      "Price": "سعر",
      "Price Details": "تفاصيل الأسعار",
      "Email": "بريد إلكتروني",
      "Full Name": "الاسم الكامل",
      "Contact Details": "بيانات المتصل",
      "Seat": "مقعد",
      "Age": "عمر",
      "Name": "اسم",
      "Passenger(S)": "ركاب)",
      "Ticket Id": "معرف التذكرة",
      "Transaction Id": "رقم المعاملة",
      "Payment Methode": "طريقة الدفع",
      "Booking Date": "تاريخ الحجز",
      "Bus Details": "تفاصيل الحافلة",
      "Completed": "مكتمل",
      "Rating": "تقييم",
      "Enter your Feedback": "أدخل ملاحظاتك",
      "Download Ticket": "تحميل تذكرة",
      "You dont`t have any booking records!": "ليس لديك أي سجلات حجز!",
      "No booking found": "لم يتم العثور على أي حجز",
      "Completed Trips": "الرحلات المكتملة",
      "Upcoming Trips": "الرحلات القادمة",
      "My Tickets": "تذاكري",
      "Tax": "ضريبة",
      "Pay from Wallet": "الدفع من المحفظة",
      "Remove": "يزيل",
      "Coupon Applied !": "تم تطبيق القسيمة!",
      "Apply Coupon": "تطبيق القسيمة",
      "Apply": "يتقدم",
      "Not Apply": "لا ينطبق",
      "Min Amount": "الحد الأدنى للمبلغ",
      "Valid untill": "ساري المفعول حتى",
      "Total Pay": "إجمالي الأجر",
      "EXTERNAL_WALLET IS": "المحفظة الخارجية هي",
      "ERROR HERE": "خطأ هنا",
      "SUCCESS PAYMENT": "الدفع الناجح",
      "gender": "جنس",
      "seat_no": "رقم المقعد",
      "age": "عمر",
      "name": "اسم",
      "Back to Home": "العودة إلى المنزل",
      "View Transaction": "عرض المعاملة",
      "Congratulation! your bus ticket is confirmed. For more details check the My Booking tab.": "تهنئة! تم تأكيد تذكرة الحافلة الخاصة بك. لمزيد من التفاصيل، تحقق من علامة التبويب تذكرتي ",
      "Booking Confirmed!": "تاكيد الحجز!",
      "Enter Age": "أدخل العمر",
      "Enter Full Name": "أدخل الاسم الكامل",
      "Business Email": "بريد العمل",
      "Business Address": "عنوان العمل",
      "Business Name": "الاسم التجاري",
      "GSTIN": "رقم ضريبة السلع والخدمات",
      "Enter Mobile Number": "أدخل رقم الجوال",
      "Enter Email id": "أدخل معرف البريد الإلكتروني",
      "Email Id": "عنوان الايميل",
      "Gender": "جنس",
      "Passenger": "راكب",
      "Passenger Details": "تفاصيل الركاب",
      "Enter Plese Input": "أدخل برجاء الإدخال",
      "(Exclusive of Taxes)": "(باستثناء الضرائب)",
      "Amount :": "كمية :",
      "Next Step": "الخطوة التالية",
      "Plese Select Boarding And Drop Point": "الرجاء تحديد نقطة الصعود والهبوط",
      "Droping Point": "نقطة الإسقاط",
      "Boarding Point": "نقطة الصعود",
      "Upper Berth": "السرير العلوي",
      "Lower Berth": "الرصيف السفلي",
      "passengers to a single booking with this operator": "الركاب إلى حجز واحد مع هذا المشغل",
      "You can not add more than": "لا يمكنك إضافة أكثر من",
      "Booked by female passenger": "حجزت من قبل راكبة",
      "Selected by you": "تم اختياره بواسطتك",
      "Booked by Others": "حجزت من قبل الآخرين",
      "Available": "متاح",
      "Know about seat types": "تعرف على أنواع المقاعد",
      "Upper Seat": "المقعد العلوي",
      "Lower Seat": "المقعد السفلي",
      "Cancellation Policy": "سياسة الإلغاء",
      "Review": "مراجعة",
      "Amenities": "وسائل الراحة",
      "Seats": "مقاعد",
      "/ Sleeper": "/ النائم",
      "ProZigzagBus fulfilled buses are not available at this time.": "حافلات ProZigzagBusbus غير متوفرة في الوقت الحالي.",
      "Change": "يتغير",
      "No reviews found": "لم يتم العثور على تعليقات",
      "AC Seater": "مقاعد مكيفة",
      "Special Offer": "عرض خاص",
      "Recent Booking": "الحجز الأخير",
      "Tomorrow": "غداً",
      "not valide": "الرجاء إدخال مدخلات صالحة",
      "Search Buses": "بحث الحافلات",
      "Enter referral code (optional)": "أدخل رمز الإحالة (اختياري)",
      "Home": "بيت",
      "My Ticket": "تذكرتي",
      "Account": "حسابt"
    },
    'en_Hindi'     : {
      "Earn":"कमाना",
      "for Each":"प्रत्येक के लिए",
      "Friend you refer":"मित्र आप देखें",
      "You get": "आपको मिला",
      "on your wallet": "आपके बटुए पर",
      "on their first complete transaction": "उनके पहले पूर्ण लेनदेन पर",
      "Friend get": "मित्र मिलो",
      "Dark Mode": "डार्क मोड",
      "Personal info": "व्यक्तिगत जानकारी",
      "Refer and earn": "देखें और कमाएँ",
      "Language": "भाषा",
      "Faq": "सामान्य प्रश्न",
      "Dark Node": "डार्क नोड",
      "ProZigzagBusbus": "टेढ़ा-मेढ़ा",
      "Your Journey, Your Way": "आपकी यात्रा, आपका रास्ता",
      "Seamless Travel Simplified": "निर्बाध यात्रा सरलीकृत",
      "Book, Ride, Enjoy": "बुक करें, घूमें, आनंद लें",
      "Explore, One Bus at a Time": "अन्वेषण करें, एक समय में एक बस",
      "Customize your travel effortlessly": "अपनी यात्रा को सहजता से अनुकूलित करें",
      "Easy booking and boarding for a stress-free journey": "तनाव मुक्त यात्रा के लिए आसान बुकिंग और बोर्डिंग",
      "Swift booking and delightful bus rides": "त्वरित बुकिंग और आनंददायक बस यात्राएँ",
      "Discover new places, one bus ride after another": "नई जगहों की खोज करें, एक के बाद एक बस यात्राएँ",
      "Welcome To ProZigzagBus": "ज़िगज़ैगबस में आपका स्वागत है",
      "We Will send OTP on this mobile number.": "हम इस मोबाइल नंबर पर ओटीपी भेजेंगे।",
      "Phone Number": "फ़ोन नंबर",
      "Enter Your Password": "अपना कूटशब्द भरें",
      "Enter Vlide Input": "कृपया मान्य इनपुट दर्ज करें",
      "PROCEED": "आगे बढ़ना",
      "Forgot Password ?": "पासवर्ड भूल गए ?",
      "Create Account or Sign in": "खाता बनाएं या साइन इन करें",
      "Enter Your Name": "अपना नाम दर्ज करें",
      "Enter Your Email Id": "अपना ईमेल आईडी दर्ज करें",
      "GENERATE OTP": "ओटीपी जनरेट करें",
      "(ONE TIME PASSWORD)": "(एक बारी पासवर्ड)",
      "HAVE A REFERRAL CODE?": "क्या आपके पास रेफरल कोड है?",
      "Don’t Have an account yet? Sign Up": "अब तक कोई खाता नहीं है? साइन अप करें",
      "ProZigzagBus": "ज़िगज़ैगबस",
      "Date": "तारीख",
      "Today": "आज",
      "From": "से",
      "To": "को",
      "to": "को",
      "Faq List": "अक्सर पूछे जाने वाले प्रश्न सूची",
      "Refer a Friend": "एक मित्र को सूचित करें",
      "Share the referral link with your friends": "रेफरल लिंक अपने दोस्तों के साथ साझा करें",
      "Logout": "लॉग आउट",
      "Yes,Logout": "हाँ, लॉगआउट करें",
      "Cancel": "रद्द करना",
      "Are you sure you want to log out?": "क्या आप लॉग आउट करना चाहते हैं?",
      "Delete Account": "खाता हटा दो",
      "Yes,Remove": "हाँ, हटाएँ",
      "Are you sure you want to delete account?": "क्या आप वाकई खाता हटाना चाहते हैं?",
      "Confirm": "पुष्टि करना",
      "Enter Input": "इनपुट दर्ज करें",
      "Profile Edit": "प्रोफ़ाइल संपादित करें",
      "About": "के बारे में",
      "General": "सामान्य",
      "My Account": "मेरा खाता",
      "100": "100",
      "300": "300",
      "500": "500",
      "1000": "1000",
      "1100": "1100",
      "1300": "1300",
      "1500": "1500",
      "1700": "1700",
      "2000": "2000",
      "Top up Amount": "टॉप अप राशि",
      "Top up": "लबालब भरना",
      "Your balance": "आपका बैलेंस",
      "Top Up": "लबालब भरना",
      "Continue": "जारी रखना",
      "Payment Getway Methode": "भुगतान गेटवे विधि",
      "CONTINUE": "जारी रखना",
      "Not Valid": "कृपया मान्य इनपुट दर्ज करें",
      "Another Top Up": "एक और टॉप अप",
      "Done For Now": "अभी के लिए हो गया",
      "Successfuly": "सफलतापूर्वक",
      "Transaction History": "ट्रांजेक्शन इतिहास",
      "My Wallet": "मेरा बटुआ",
      "Image saved in gallery": "छवि गैलरी में सहेजी गई",
      "Total Price": "कुल कीमत",
      "Wallet": "बटुआ",
      "Discount": "छूट",
      "Price": "कीमत",
      "Price Details": "मूल्य विवरण",
      "Email": "ईमेल",
      "Full Name": "पूरा नाम",
      "Contact Details": "सम्पर्क करने का विवरण",
      "Seat": "सीट",
      "Age": "आयु",
      "Name": "नाम",
      "Passenger(S)": "यात्री(ओं)",
      "Ticket Id": "टिकट आईडी",
      "Transaction Id": "लेनदेन आईडी",
      "Payment Methode": "भुगतान विधि",
      "Booking Date": "बुक करने की तिथि",
      "Bus Details": "बस विवरण",
      "Completed": "पुरा होना।",
      "Rating": "रेटिंग",
      "Enter your Feedback": "अपनी प्रतिक्रिया दर्ज करें",
      "Download Ticket": "टिकट डाउनलोड करें",
      "You dont`t have any booking records!": "आपके पास कोई बुकिंग रिकॉर्ड नहीं है!",
      "No booking found": "कोई बुकिंग नहीं मिली",
      "Completed Trips": "यात्राएँ पूरी कीं",
      "Upcoming Trips": "आगामी यात्राएँ",
      "My Tickets": "मेरे टिकट",
      "Tax": "कर",
      "Pay from Wallet": "वॉलेट से भुगतान करें",
      "Remove": "निकालना",
      "Coupon Applied !": "कूपन लागू!",
      "Apply Coupon": "कूपन के लिए आवेदन करो",
      "Apply": "आवेदन करना",
      "Not Apply": "प्रयोग नहीं किया",
      "Min Amount": "न्यूनतम राशि",
      "Valid untill": "इस समय तक मान्य",
      "Total Pay": "कुल वेतन",
      "EXTERNAL_WALLET IS": "बाहरी_वॉलेट है",
      "ERROR HERE": "यहाँ त्रुटि",
      "SUCCESS PAYMENT": "सफलता भुगतान",
      "gender": "लिंग",
      "seat_no": "सीट संख्या",
      "age": "आयु",
      "name": "नाम",
      "Back to Home": "घर वापिस जा रहा हूँ",
      "View Transaction": "लेन-देन देखें",
      "Congratulation! your bus ticket is confirmed. For more details check the My Booking tab.": "बधाई हो! आपका बस टिकट कन्फर्म हो गया है. अधिक जानकारी के लिए मेरा टिकट टैब देखें।",
      "Booking Confirmed!": "बुकिंग संपुष्ट!",
      "Enter Age": "आयु दर्ज करें",
      "Enter Full Name": "पूरा नाम दर्ज करें",
      "Business Email": "बिजनेस ईमेल",
      "Business Address": "व्यावसायिक पता",
      "Business Name": "व्यवसाय का नाम",
      "GSTIN": "जीएसटीआईएन",
      "Enter Mobile Number": "मोबाइल नंबर दर्ज करें",
      "Enter Email id": "ईमेल आईडी दर्ज करें",
      "Email Id": "ईमेल आईडी",
      "Gender": "लिंग",
      "Passenger": "यात्री",
      "Passenger Details": "यात्री विवरण",
      "Enter Plese Input": "कृपया इनपुट दर्ज करें",
      "(Exclusive of Taxes)": "(करों को छोड़कर)",
      "Amount :": "मात्रा :",
      "Next Step": "अगला कदम",
      "Plese Select Boarding And Drop Point": "कृपया बोर्डिंग और ड्रॉप प्वाइंट का चयन करें",
      "Droping Point": "ड्रॉपिंग पॉइंट",
      "Boarding Point": "बोर्डिंग प्वाइंट",
      "Upper Berth": "ऊपर की शैय्या",
      "Lower Berth": "निचली शायिका",
      "passengers to a single booking with this operator": "इस ऑपरेटर के साथ यात्रियों को एकल बुकिंग",
      "You can not add more than": "आप इससे अधिक नहीं जोड़ सकते",
      "Booked by female passenger": "महिला यात्री द्वारा बुक किया गया",
      "Selected by you": "आपके द्वारा चयनित",
      "Booked by Others": "दूसरों द्वारा बुक किया गया",
      "Available": "उपलब्ध",
      "Know about seat types": "जानिए सीट के प्रकार के बारे में",
      "Upper Seat": "ऊपरी सीट",
      "Lower Seat": "निचली सीट",
      "Cancellation Policy": "रद्द करने की नीति",
      "Review": "समीक्षा",
      "Amenities": "सुविधाएं",
      "Seats": "सीटें",
      "/ Sleeper": "/ स्लीपर",
      "ProZigzagBus fulfilled buses are not available at this time.": "ज़िगज़ैगबस से सुसज्जित बसें इस समय उपलब्ध नहीं हैं।",
      "Change": "परिवर्तन",
      "No reviews found": "कोई समीक्षा नहीं मिली",
      "AC Seater": "एसी सीटर",
      "Special Offer": "विशेष पेशकश",
      "Recent Booking": "हालिया बुकिंग",
      "Tomorrow": "कल",
      "not valide": "कृपया मान्य इनपुट दर्ज करें",
      "Search Buses": "बसे खोजें",
      "Enter referral code (optional)": "रेफरल कोड दर्ज करें (वैकल्पिक)",
      "Home": "घर",
      "My Ticket": "मेरा टिकट",
      "Account": "खाताt"
    },
    'en_Gujarati'  : {
      "Earn":"કમાઓ",
      "for Each":"દરેક માટે",
      "Friend you refer":"મિત્ર તમે સંદર્ભ લો",
      "You get": "તમે મેળવો",
      "on your wallet": "તમારા વૉલેટ પર",
      "on their first complete transaction": "તેમના પ્રથમ સંપૂર્ણ વ્યવહાર પર",
      "Friend get": "મિત્ર મળે છે",
      "Dark Mode": "ડાર્ક મોડ",
      "Personal info": "વ્યક્તિગત માહિતી",
      "Refer and earn": "સંદર્ભ લો અને કમાઓ",
      "Language": "ભાષા",
      "Faq": "FAQ",
      "Dark Node": "ડાર્ક નોડ",
      "ProZigzagBusbus": "ઝિગઝેગબસ",
      "Your Journey, Your Way": "તમારી જર્ની, તમારો રસ્તો",
      "Seamless Travel Simplified": "સીમલેસ મુસાફરી સરળ",
      "Book, Ride, Enjoy": "બુક કરો, રાઈડ કરો, એન્જોય કરો",
      "Explore, One Bus at a Time": "અન્વેષણ કરો, એક સમયે એક બસ",
      "Customize your travel effortlessly": "તમારી મુસાફરીને સરળતાથી કસ્ટમાઇઝ કરો",
      "Easy booking and boarding for a stress-free journey": "તણાવમુક્ત પ્રવાસ માટે સરળ બુકિંગ અને બોર્ડિંગ",
      "Swift booking and delightful bus rides": "સ્વિફ્ટ બુકિંગ અને આનંદદાયક બસ સવારી",
      "Discover new places, one bus ride after another": "નવા સ્થાનો શોધો, એક પછી એક બસની સવારી",
      "Welcome To ProZigzagBus": "ઝિગઝેગબસમાં આપનું સ્વાગત છે",
      "We Will send OTP on this mobile number.": "અમે આ મોબાઈલ નંબર પર OTP મોકલીશું.",
      "Phone Number": "ફોન નંબર",
      "Enter Your Password": "તમારો પાસવર્ડ નાખો",
      "Enter Vlide Input": "કૃપા કરીને માન્ય ઇનપુટ્સ દાખલ કરો",
      "PROCEED": "આગળ વધો",
      "Forgot Password ?": "પાસવર્ડ ભૂલી ગયા છો?",
      "Create Account or Sign in": "એકાઉન્ટ બનાવો અથવા સાઇન ઇન કરો",
      "Enter Your Name": "તમારું નામ દાખલ કરો",
      "Enter Your Email Id": "તમારું ઈમેલ આઈડી દાખલ કરો",
      "GENERATE OTP": "OTP જનરેટ કરો",
      "(ONE TIME PASSWORD)": "(એક સમયનો પાસવર્ડ)",
      "HAVE A REFERRAL CODE?": "શું તમારી પાસે રેફરલ કોડ છે?",
      "Don’t Have an account yet? Sign Up": "હજુ સુધી એકાઉન્ટ નથી? સાઇન અપ કરો",
      "ProZigzagBus": "ઝિગઝેગબસ",
      "Date": "તારીખ",
      "Today": "આજે",
      "From": "થી",
      "To": "પ્રતિ",
      "to": "પ્રતિ",
      "Faq List": "FAQ સૂચિ",
      "Refer a Friend": "મિત્રનો સંદર્ભ લો",
      "Share the referral link with your friends": "તમારા મિત્રો સાથે રેફરલ લિંક શેર કરો",
      "Logout": "લૉગ આઉટ",
      "Yes,Logout": "હા, લોગઆઉટ",
      "Cancel": "રદ કરો",
      "Are you sure you want to log out?": "શું તમે ખરેખર લૉગ આઉટ કરવા માંગો છો?",
      "Delete Account": "એકાઉન્ટ કાઢી નાખો",
      "Yes,Remove": "હા, દૂર કરો",
      "Are you sure you want to delete account?": "શું તમે ખરેખર એકાઉન્ટ કાઢી નાખવા માંગો છો?",
      "Confirm": "પુષ્ટિ કરો",
      "Enter Input": "ઇનપુટ દાખલ કરો",
      "Profile Edit": "પ્રોફાઇલ સંપાદિત કરો",
      "About": "વિશે",
      "General": "જનરલ",
      "My Account": "મારું ખાતું",
      "100": "100",
      "300": "300",
      "500": "500",
      "1000": "1000",
      "1100": "1100",
      "1300": "1300",
      "1500": "1500",
      "1700": "1700",
      "2000": "2000",
      "Top up Amount": "ટોપ અપ રકમ",
      "Top up": "ટોચ",
      "Your balance": "તમારું બેલેન્સ",
      "Top Up": "ટોચ",
      "Continue": "ચાલુ રાખો",
      "Payment Getway Methode": "ચુકવણી ગેટવે પદ્ધતિ",
      "CONTINUE": "ચાલુ રાખો",
      "Not Valid": "કૃપા કરીને માન્ય ઇનપુટ્સ દાખલ કરો",
      "Another Top Up": "અન્ય ટોપ અપ",
      "Done For Now": "હમણાં માટે થઈ ગયું",
      "Successfuly": "સફળતાપૂર્વક",
      "Transaction History": "વ્યવહાર ઇતિહાસ",
      "My Wallet": "મારું પાકીટ",
      "Image saved in gallery": "છબી ગેલેરીમાં સાચવી",
      "Total Price": "કુલ કિંમત",
      "Wallet": "વૉલેટ",
      "Discount": "ડિસ્કાઉન્ટ",
      "Price": "કિંમત",
      "Price Details": "કિંમત વિગતો",
      "Email": "ઈમેલ",
      "Full Name": "પૂરું નામ",
      "Contact Details": "સંપર્ક વિગતો",
      "Seat": "બેઠક",
      "Age": "ઉંમર",
      "Name": "નામ",
      "Passenger(S)": "પેસેન્જર(ઓ)",
      "Ticket Id": "ટિકિટ આઈડી",
      "Transaction Id": "ટ્રાન્ઝેક્શન આઈડી",
      "Payment Methode": "ચુકવણી પદ્ધતિ",
      "Booking Date": "બુકિંગ તારીખ",
      "Bus Details": "બસની વિગતો",
      "Completed": "પૂર્ણ થયું",
      "Rating": "રેટિંગ",
      "Enter your Feedback": "તમારો પ્રતિસાદ દાખલ કરો",
      "Download Ticket": "ટિકિટ ડાઉનલોડ કરો",
      "You dont`t have any booking records!": "તમારી પાસે કોઈ બુકિંગ રેકોર્ડ્સ નથી!",
      "No booking found": "કોઈ બુકિંગ મળ્યું નથી",
      "Completed Trips": "પૂર્ણ કરેલ પ્રવાસો",
      "Upcoming Trips": "આગામી પ્રવાસો",
      "My Tickets": "મારી ટિકિટ",
      "Tax": "કર",
      "Pay from Wallet": "વૉલેટમાંથી ચુકવણી કરો",
      "Remove": "દૂર કરો",
      "Coupon Applied !": "કૂપન લાગુ!",
      "Apply Coupon": "કૂપન લાગુ કરો",
      "Apply": "અરજી કરો",
      "Not Apply": "લાગુ નથી",
      "Min Amount": "ન્યૂનતમ રકમ",
      "Valid untill": "સુધી માન્ય",
      "Total Pay": "કુલ પગાર",
      "EXTERNAL_WALLET IS": "EXTERNAL_WALLET છે",
      "ERROR HERE": "અહીં ભૂલ",
      "SUCCESS PAYMENT": "સક્સેસ પેમેન્ટ",
      "gender": "લિંગ",
      "seat_no": "સીટ_નં",
      "age": "ઉંમર",
      "name": "નામ",
      "Back to Home": "ઘરે પાછા",
      "View Transaction": "વ્યવહાર જુઓ",
      "Congratulation! your bus ticket is confirmed. For more details check the My Booking tab.": "અભિનંદન! તમારી બસ ટિકિટ કન્ફર્મ થઈ ગઈ છે. વધુ વિગતો માટે મારી ટિકિટ ટેબ તપાસો.",
      "Booking Confirmed!": "બુકિંગ કન્ફર્મ!",
      "Enter Age": "ઉંમર દાખલ કરો",
      "Enter Full Name": "પૂરું નામ દાખલ કરો",
      "Business Email": "વ્યવસાય ઇમેઇલ",
      "Business Address": "વ્યવસાયનું સરનામું",
      "Business Name": "વ્યવસાયનું નામ",
      "GSTIN": "GSTIN",
      "Enter Mobile Number": "મોબાઈલ નંબર દાખલ કરો",
      "Enter Email id": "ઈમેલ આઈડી દાખલ કરો",
      "Email Id": "ઈમેલ આઈડી",
      "Gender": "જાતિ",
      "Passenger": "પેસેન્જર",
      "Passenger Details": "પેસેન્જર વિગતો",
      "Enter Plese Input": "કૃપા કરીને ઇનપુટ દાખલ કરો",
      "(Exclusive of Taxes)": "(કર સિવાય)",
      "Amount :": "રકમ :",
      "Next Step": "આગળનું પગલું",
      "Plese Select Boarding And Drop Point": "કૃપા કરીને બોર્ડિંગ અને ડ્રોપ પોઇન્ટ પસંદ કરો",
      "Droping Point": "ડ્રોપિંગ પોઈન્ટ",
      "Boarding Point": "બોર્ડિંગ પોઈન્ટ",
      "Upper Berth": "અપર બર્થ",
      "Lower Berth": "લોઅર બર્થ",
      "passengers to a single booking with this operator": "આ ઓપરેટર સાથે એક જ બુકિંગ માટે મુસાફરો",
      "You can not add more than": "કરતાં વધુ ઉમેરી શકતા નથી",
      "Booked by female passenger": "મહિલા મુસાફર દ્વારા બુક કરાવેલ",
      "Selected by you": "તમારા દ્વારા પસંદ કરેલ",
      "Booked by Others": "અન્ય લોકો દ્વારા બુક કરાયેલ",
      "Available": "ઉપલબ્ધ છે",
      "Know about seat types": "સીટના પ્રકારો વિશે જાણો",
      "Upper Seat": "અપર સીટ",
      "Lower Seat": "નીચલી સીટ",
      "Cancellation Policy": "રદીકરણ નીતિ",
      "Review": "સમીક્ષા",
      "Amenities": "સુવિધાઓ",
      "Seats": "બેઠકો",
      "/ Sleeper": "/ સ્લીપર",
      "ProZigzagBus fulfilled buses are not available at this time.": "ઝિગઝેગબસ પરિપૂર્ણ બસો આ સમયે ઉપલબ્ધ નથી.",
      "Change": "બદલો",
      "No reviews found": "કોઈ સમીક્ષાઓ મળી નથી",
      "AC Seater": "એસી સીટર",
      "Special Offer": "ખાસ ઓફર",
      "Recent Booking": "તાજેતરનું બુકિંગ",
      "Tomorrow": "કાલે",
      "not valide": "કૃપા કરીને માન્ય ઇનપુટ્સ દાખલ કરો",
      "Search Buses": "બસ શોધો",
      "Enter referral code (optional)": "રેફરલ કોડ દાખલ કરો (વૈકલ્પિક)",
      "Home": "ઘર",
      "My Ticket": "મારી ટિકિટ",
      "Account": "એકાઉન્ટt"
    },
    'en_African'   : {
      "Earn":"Verdien",
      "for Each":"vir elke",
      "Friend you refer":"Vriend wat jy verwys",
      "You get": "Jy kry",
      "on your wallet": "op jou beursie",
      "on their first complete transaction": "op hul eerste volledige transaksie",
      "Friend get": "Vriend kry",
      "Dark Mode": "Donker modus",
      "Personal info": "Persoonlike inligting",
      "Refer and earn": "Verwys en verdien",
      "Language": "Taal",
      "Faq": "Gereelde vrae",
      "Dark Node": "Donker Node",
      "ProZigzagBusbus": "sigsagbus",
      "Your Journey, Your Way": "Jou Reis, Jou Weg",
      "Seamless Travel Simplified": "Naatlose reis vereenvoudig",
      "Book, Ride, Enjoy": "Bespreek, ry, geniet",
      "Explore, One Bus at a Time": "Verken, een bus op 'n slag",
      "Customize your travel effortlessly": "Pas jou reis moeiteloos aan",
      "Easy booking and boarding for a stress-free journey": "Maklike bespreking en instap vir 'n stresvrye reis",
      "Swift booking and delightful bus rides": "Vinnige bespreking en heerlike busritte",
      "Discover new places, one bus ride after another": "Ontdek nuwe plekke, een busrit na die ander",
      "Welcome To ProZigzagBus": "Welkom by Sigsagbus",
      "We Will send OTP on this mobile number.": "Ons sal OTP op hierdie selfoonnommer stuur.",
      "Phone Number": "Telefoon nommer",
      "Enter Your Password": "Sleutel jou wagwoord in",
      "Enter Vlide Input": "Voer asseblief geldige invoere in",
      "PROCEED": "VOORTGAAN",
      "Forgot Password ?": "Wagwoord vergeet ?",
      "Create Account or Sign in": "Skep rekening of meld aan",
      "Enter Your Name": "Gee jou naam",
      "Enter Your Email Id": "Voer jou e-pos-ID in",
      "GENERATE OTP": "GENEREER OTP",
      "(ONE TIME PASSWORD)": "(EENMAAL WAGWOORD)",
      "HAVE A REFERRAL CODE?": "HET 'N VERWYSINGSKODE?",
      "Don’t Have an account yet? Sign Up": "Het jy nog nie 'n rekening nie? Teken aan",
      "ProZigzagBus": "Sigsagbus",
      "Date": "Datum",
      "Today": "Vandag",
      "From": "Van",
      "To": "Om",
      "to": "aan",
      "Faq List": "Faq Lys",
      "Refer a Friend": "Verwys 'n Vriend",
      "Share the referral link with your friends": "Deel die verwysingskakel met jou vriende",
      "Logout": "Teken uit",
      "Yes,Logout": "Ja, Teken uit",
      "Cancel": "Kanselleer",
      "Are you sure you want to log out?": "Is jy seker jy wil afmeld?",
      "Delete Account": "Skrap rekening",
      "Yes,Remove": "Ja, verwyder",
      "Are you sure you want to delete account?": "Is jy seker jy wil rekening uitvee?",
      "Confirm": "Bevestig",
      "Enter Input": "Voer Invoer in",
      "Profile Edit": "Wysig profiel",
      "About": "Oor",
      "General": "Algemeen",
      "My Account": "My rekening",
      "100": "100",
      "300": "300",
      "500": "500",
      "1000": "1000",
      "1100": "1100",
      "1300": "1300",
      "1500": "1500",
      "1700": "1700",
      "2000": "2000",
      "Top up Amount": "Vul Bedrag aan",
      "Top up": "Vul aan",
      "Your balance": "Jou balans",
      "Top Up": "Vul aan",
      "Continue": "Aanhou",
      "Payment Getway Methode": "Betaling Getway Metode",
      "CONTINUE": "AANHOU",
      "Not Valid": "Voer asseblief geldige invoere in",
      "Another Top Up": "Nog 'n Top Up",
      "Done For Now": "Vir Nou klaar",
      "Successfuly": "Suksesvol",
      "Transaction History": "Transaksiegeskiedenis",
      "My Wallet": "My beursie",
      "Image saved in gallery": "Prent gestoor in gallery",
      "Total Price": "Totale prys",
      "Wallet": "Beursie",
      "Discount": "Afslag",
      "Price": "Prys",
      "Price Details": "Prys besonderhede",
      "Email": "E-pos",
      "Full Name": "Volle naam",
      "Contact Details": "Kontakbesonderhede",
      "Seat": "Sitplek",
      "Age": "Ouderdom",
      "Name": "Naam",
      "Passenger(S)": "Passasier(S)",
      "Ticket Id": "Kaartjie-ID",
      "Transaction Id": "Transaksie ID",
      "Payment Methode": "Betaalmetode",
      "Booking Date": "Besprekingsdatum",
      "Bus Details": "Busbesonderhede",
      "Completed": "Voltooi",
      "Rating": "Gradering",
      "Enter your Feedback": "Voer jou terugvoer in",
      "Download Ticket": "Laai Kaartjie af",
      "You dont`t have any booking records!": "Jy het geen besprekingsrekords nie!",
      "No booking found": "Geen bespreking gevind nie",
      "Completed Trips": "Voltooide reise",
      "Upcoming Trips": "Komende reise",
      "My Tickets": "My Kaartjies",
      "Tax": "Belasting",
      "Pay from Wallet": "Betaal uit Wallet",
      "Remove": "Verwyder",
      "Coupon Applied !": "Koepon toegepas!",
      "Apply Coupon": "Pas koepon toe",
      "Apply": "Doen aansoek",
      "Not Apply": "Nie aansoek doen nie",
      "Min Amount": "Min hoeveelheid",
      "Valid untill": "Geldig tot",
      "Total Pay": "Totale betaling",
      "EXTERNAL_WALLET IS": "EXTERNAL_WALLET IS",
      "ERROR HERE": "FOUT HIER",
      "SUCCESS PAYMENT": "SUKSES BETALING",
      "gender": "geslag",
      "seat_no": "sitplek_nr",
      "age": "ouderdom",
      "name": "naam",
      "Back to Home": "Terug huistoe",
      "View Transaction": "Bekyk transaksie",
      "Congratulation! your bus ticket is confirmed. For more details check the My Booking tab.": "Baie geluk! jou buskaartjie is bevestig. Vir meer besonderhede, kyk na die My Kaartjie-oortjie.",
      "Booking Confirmed!": "Bespreking bevestig!",
      "Enter Age": "Voer ouderdom in",
      "Enter Full Name": "Voer volle naam in",
      "Business Email": "Besigheid e-pos",
      "Business Address": "Besigheidsadres",
      "Business Name": "besigheids naam",
      "GSTIN": "GSTIN",
      "Enter Mobile Number": "Voer selfoonnommer in",
      "Enter Email id": "Voer e-pos-ID in",
      "Email Id": "E-pos identiteit",
      "Gender": "Geslag",
      "Passenger": "Passasier",
      "Passenger Details": "Passasierbesonderhede",
      "Enter Plese Input": "Voer asseblief Invoer in",
      "(Exclusive of Taxes)": "(Belasting uitgesluit)",
      "Amount :": "Bedrag:",
      "Next Step": "Volgende stap",
      "Plese Select Boarding And Drop Point": "Kies asseblief instap- en aflaaipunt",
      "Droping Point": "Afvalpunt",
      "Boarding Point": "Instappunt",
      "Upper Berth": "Boonste Kooi",
      "Lower Berth": "Onderste bed",
      "passengers to a single booking with this operator": "passasiers na 'n enkele bespreking by hierdie operateur",
      "You can not add more than": "Jy kan nie meer as byvoeg nie",
      "Booked by female passenger": "Bespreek deur vroulike passasier",
      "Selected by you": "Gekies deur jou",
      "Booked by Others": "Bespreek deur ander",
      "Available": "Beskikbaar",
      "Know about seat types": "Weet van sitplektipes",
      "Upper Seat": "Boonste sitplek",
      "Lower Seat": "Laer sitplek",
      "Cancellation Policy": "Kansellasie beleid",
      "Review": "Resensie",
      "Amenities": "Geriewe",
      "Seats": "Sitplekke",
      "/ Sleeper": "/ Slaper",
      "ProZigzagBus fulfilled buses are not available at this time.": "ProZigzagBusbus vervulde busse is nie tans beskikbaar nie.",
      "Change": "Verander",
      "No reviews found": "Geen resensies gevind nie",
      "AC Seater": "AC sitplek",
      "Special Offer": "Spesiale aanbod",
      "Recent Booking": "Onlangse bespreking",
      "Tomorrow": "Môre",
      "not valide": "Voer asseblief geldige invoere in",
      "Search Buses": "Soek Busse",
      "Enter referral code (optional)": "Voer verwysingskode in (opsioneel)",
      "Home": "Tuis",
      "My Ticket": "My Kaartjie",
      "Account": "Rekeningt"
    },
    'en_Bangali'   : {
      "Earn":"আয় করুন",
      "for Each":"প্রতিটির জন্য",
      "Friend you refer":"বন্ধু তুমি রেফার করো",
      "You get": "তুমি পাও",
      "on your wallet": "আপনার ওয়ালেটে",
      "on their first complete transaction": "তাদের প্রথম সম্পূর্ণ লেনদেনে",
      "Friend get": "বন্ধু পান",
      "Dark Mode": "ডার্ক মোড",
      "Personal info": "ব্যাক্তিগত তথ্য",
      "Refer and earn": "রেফার করুন এবং উপার্জন করুন",
      "Language": "ভাষা",
      "Faq": "প্রশ্ন",
      "Dark Node": "ডার্ক নোড",
      "ProZigzagBusbus": "জিগজ্যাগবাস",
      "Your Journey, Your Way": "আপনার যাত্রা, আপনার পথ",
      "Seamless Travel Simplified": "বিরামহীন ভ্রমণ সরলীকৃত",
      "Book, Ride, Enjoy": "বই, রাইড, উপভোগ করুন",
      "Explore, One Bus at a Time": "অন্বেষণ, এক সময়ে একটি বাস",
      "Customize your travel effortlessly": "অনায়াসে আপনার ভ্রমণ কাস্টমাইজ করুন",
      "Easy booking and boarding for a stress-free journey": "চাপমুক্ত যাত্রার জন্য সহজ বুকিং এবং বোর্ডিং",
      "Swift booking and delightful bus rides": "সুইফট বুকিং এবং আনন্দদায়ক বাস যাত্রা",
      "Discover new places, one bus ride after another": "নতুন জায়গা আবিষ্কার করুন, একের পর এক বাসে চড়ুন",
      "Welcome To ProZigzagBus": "জিগজ্যাগবাসে স্বাগতম",
      "We Will send OTP on this mobile number.": "আমরা এই মোবাইল নম্বরে OTP পাঠাব।",
      "Phone Number": "ফোন নম্বর",
      "Enter Your Password": "আপনার পাসওয়ার্ড লিখুন",
      "Enter Vlide Input": "বৈধ ইনপুট লিখুন",
      "PROCEED": "এগিয়ে যান",
      "Forgot Password ?": "পাসওয়ার্ড ভুলে গেছেন ?",
      "Create Account or Sign in": "অ্যাকাউন্ট তৈরি করুন বা সাইন ইন করুন",
      "Enter Your Name": "আপনার নাম প্রবেশ করুন",
      "Enter Your Email Id": "আপনার ইমেইল আইডি লিখুন",
      "GENERATE OTP": "ওটিপি জেনারেট করুন",
      "(ONE TIME PASSWORD)": "(এক সময়ের পাসওয়ার্ড)",
      "HAVE A REFERRAL CODE?": "একটি রেফারেল কোড আছে?",
      "Don’t Have an account yet? Sign Up": "কোনো একাউন্ট এখনও আছে না? নিবন্ধন করুন",
      "ProZigzagBus": "জিগজ্যাগবাস",
      "Date": "তারিখ",
      "Today": "আজ",
      "From": "থেকে",
      "To": "প্রতি",
      "to": "প্রতি",
      "Faq List": "FAQ তালিকা",
      "Refer a Friend": "একটা বন্ধু উল্লেখ কর",
      "Share the referral link with your friends": "আপনার বন্ধুদের সাথে রেফারেল লিঙ্ক শেয়ার করুন",
      "Logout": "প্রস্থান",
      "Yes,Logout": "হ্যাঁ, লগআউট করুন",
      "Cancel": "বাতিল করুন",
      "Are you sure you want to log out?": "আপনি লগ আউট করতে চান?",
      "Delete Account": "হিসাব মুছে ফেলা",
      "Yes,Remove": "হ্যাঁ, সরান",
      "Are you sure you want to delete account?": "আপনি কি নিশ্চিত আপনি অ্যাকাউন্ট মুছে ফেলতে চান?",
      "Confirm": "নিশ্চিত করুন",
      "Enter Input": "ইনপুট লিখুন",
      "Profile Edit": "জীবন বৃত্তান্ত সম্পাদনা",
      "About": "সম্পর্কিত",
      "General": "সাধারণ",
      "My Account": "আমার অ্যাকাউন্ট",
      "100": "100",
      "300": "300",
      "500": "500",
      "1000": "1000",
      "1100": "1100",
      "1300": "1300",
      "1500": "1500",
      "1700": "1700",
      "2000": "2000",
      "Top up Amount": "টপ আপ পরিমাণ",
      "Top up": "টপ আপ",
      "Your balance": "আপনার ব্যালেন্স",
      "Top Up": "টপ আপ",
      "Continue": "চালিয়ে যান",
      "Payment Getway Methode": "পেমেন্ট গেটওয়ে পদ্ধতি",
      "CONTINUE": "চালিয়ে যান",
      "Not Valid": "বৈধ ইনপুট লিখুন",
      "Another Top Up": "আরেকটি টপ আপ",
      "Done For Now": "এখন জন্য সম্পন্ন",
      "Successfuly": "সফলভাবে",
      "Transaction History": "আপনি কি আমার সাথে কি করতে চান",
      "My Wallet": "আমার মানিব্যাগ",
      "Image saved in gallery": "ছবি গ্যালারিতে সংরক্ষিত",
      "Total Price": "মোট দাম",
      "Wallet": "ওয়ালেট",
      "Discount": "ছাড়",
      "Price": "দাম",
      "Price Details": "মূল্য বিবরণ",
      "Email": "ইমেইল",
      "Full Name": "পুরো নাম",
      "Contact Details": "যোগাযোগের ঠিকানা",
      "Seat": "আসন",
      "Age": "বয়স",
      "Name": "নাম",
      "Passenger(S)": "যাত্রী(গুলি)",
      "Ticket Id": "টিকিট আইডি",
      "Transaction Id": "লেনদেন নাম্বার",
      "Payment Methode": "পেমেন্ট পদ্ধতি",
      "Booking Date": "বুকিং তারিখ",
      "Bus Details": "বাসের বিবরণ",
      "Completed": "সম্পন্ন",
      "Rating": "রেটিং",
      "Enter your Feedback": "আপনার প্রতিক্রিয়া লিখুন",
      "Download Ticket": "টিকিট ডাউনলোড করুন",
      "You dont`t have any booking records!": "আপনার কোন বুকিং রেকর্ড নেই!",
      "No booking found": "কোনো বুকিং পাওয়া যায়নি",
      "Completed Trips": "সম্পূর্ণ ট্রিপ",
      "Upcoming Trips": "আসন্ন ট্রিপ",
      "My Tickets": "আমার টিকেট",
      "Tax": "ট্যাক্স",
      "Pay from Wallet": "ওয়ালেট থেকে অর্থ প্রদান করুন",
      "Remove": "অপসারণ",
      "Coupon Applied !": "কুপন প্রয়োগ করা হয়েছে !",
      "Apply Coupon": "কুপন প্রয়োগ করুন",
      "Apply": "আবেদন করুন",
      "Not Apply": "প্রযোজ্য নয়",
      "Min Amount": "ন্যূনতম পরিমাণ",
      "Valid untill": "পর্যন্ত বৈধ",
      "Total Pay": "মোট বেতন",
      "EXTERNAL_WALLET IS": "EXTERNAL_WALLET IS৷",
      "ERROR HERE": "এখানে ত্রুটি",
      "SUCCESS PAYMENT": "সফল পেমেন্ট",
      "gender": "লিঙ্গ",
      "seat_no": "আসন_সংখ্যা",
      "age": "বয়স",
      "name": "নাম",
      "Back to Home": "বাড়িতে ফিরে যাও",
      "View Transaction": "লেনদেন দেখুন",
      "Congratulation! your bus ticket is confirmed. For more details check the My Booking tab.": "অভিনন্দন! আপনার বাসের টিকিট নিশ্চিত হয়েছে। আরো বিস্তারিত জানার জন্য আমার টিকিট ট্যাব চেক করুন.",
      "Booking Confirmed!": "বুকিং নিশ্চিত!",
      "Enter Age": "বয়স লিখুন",
      "Enter Full Name": "পুরো নাম লিখুন",
      "Business Email": "ব্যবসা ইমেল",
      "Business Address": "ব্যবসা ঠিকানা",
      "Business Name": "প্রাতিষ্ঠানিক নাম",
      "GSTIN": "জিএসটিআইএন",
      "Enter Mobile Number": "মোবাইল নম্বর লিখুন",
      "Enter Email id": "ইমেইল আইডি দিন",
      "Email Id": "ইমেইল আইডি",
      "Gender": "লিঙ্গ",
      "Passenger": "যাত্রী",
      "Passenger Details": "যাত্রীর বিবরণ",
      "Enter Plese Input": "অনুগ্রহ করে ইনপুট লিখুন",
      "(Exclusive of Taxes)": "(কর ব্যতীত)",
      "Amount :": "পরিমাণ:",
      "Next Step": "পরবর্তী পর্ব",
      "Plese Select Boarding And Drop Point": "অনুগ্রহ করে বোর্ডিং এবং ড্রপ পয়েন্ট নির্বাচন করুন",
      "Droping Point": "ড্রপিং পয়েন্ট",
      "Boarding Point": "বোর্ডিং পয়েন্ট",
      "Upper Berth": "আপার বার্থ",
      "Lower Berth": "লোয়ার বার্থ",
      "passengers to a single booking with this operator": "এই অপারেটরের সাথে একক বুকিংয়ে যাত্রীরা",
      "You can not add more than": "এর বেশি যোগ করতে পারবেন না",
      "Booked by female passenger": "মহিলা যাত্রী দ্বারা বুক করা",
      "Selected by you": "আপনার দ্বারা নির্বাচিত",
      "Booked by Others": "অন্যদের দ্বারা বুক করা",
      "Available": "পাওয়া যায়",
      "Know about seat types": "আসনের ধরন সম্পর্কে জানুন",
      "Upper Seat": "উপরের আসন",
      "Lower Seat": "নিচের সিট",
      "Cancellation Policy": "বাতিলকরণ নীতি",
      "Review": "পুনঃমূল্যায়ন",
      "Amenities": "সুযোগ-সুবিধা",
      "Seats": "আসন",
      "/ Sleeper": "/ স্লিপার",
      "ProZigzagBus fulfilled buses are not available at this time.": "জিগজ্যাগবাস পরিপূর্ণ বাস এই সময়ে উপলব্ধ নেই.",
      "Change": "পরিবর্তন",
      "No reviews found": "কোন পর্যালোচনা পাওয়া যায়নি",
      "AC Seater": "এসি সিটার",
      "Special Offer": "বিশেষ প্রস্তাব",
      "Recent Booking": "সাম্প্রতিক বুকিং",
      "Tomorrow": "কাল",
      "not valide": "বৈধ ইনপুট লিখুন",
      "Search Buses": "বাস অনুসন্ধান করুন",
      "Enter referral code (optional)": "রেফারেল কোড লিখুন (ঐচ্ছিক)",
      "Home": "বাড়ি",
      "My Ticket": "আমার টিকিট",
      "Account": "হিসাবt"
    },
    'en_Indonesiya': {
      "Earn":"Menghasilkan",
      "for Each":"untuk setiap",
      "Friend you refer":"Teman yang Anda referensikan",
      "You get": "Anda mendapatkan",
      "on your wallet": "di dompetmu",
      "on their first complete transaction": "pada transaksi lengkap pertama mereka",
      "Friend get": "Teman dapatkan",
      "Dark Mode": "Mode Gelap",
      "Personal info": "Informasi pribadi",
      "Refer and earn": "Rujuk dan dapatkan",
      "Language": "Bahasa",
      "Faq": "Pertanyaan Umum",
      "Dark Node": "Node Gelap",
      "ProZigzagBusbus": "ProZigzagBusbus",
      "Your Journey, Your Way": "Perjalananmu, Jalanmu",
      "Seamless Travel Simplified": "Perjalanan Mulus Disederhanakan",
      "Book, Ride, Enjoy": "Pesan, Naik, Nikmati",
      "Explore, One Bus at a Time": "Jelajahi, Satu Bus Sekaligus",
      "Customize your travel effortlessly": "Sesuaikan perjalanan Anda dengan mudah",
      "Easy booking and boarding for a stress-free journey": "Pemesanan dan boarding yang mudah untuk perjalanan bebas stres",
      "Swift booking and delightful bus rides": "Pemesanan cepat dan perjalanan bus yang menyenangkan",
      "Discover new places, one bus ride after another": "Temukan tempat-tempat baru, naik bus demi bus",
      "Welcome To ProZigzagBus": "Selamat Datang di ProZigzagBusbus",
      "We Will send OTP on this mobile number.": "Kami Akan mengirimkan OTP pada nomor ponsel ini.",
      "Phone Number": "Nomor telepon",
      "Enter Your Password": "Masukkan Kata Sandi Anda",
      "Enter Vlide Input": "Silakan masukkan input yang valid",
      "PROCEED": "MELANJUTKAN",
      "Forgot Password ?": "Tidak ingat kata sandi ?",
      "Create Account or Sign in": "Buat Akun atau Masuk",
      "Enter Your Name": "Masukkan nama Anda",
      "Enter Your Email Id": "Masukkan Id Email Anda",
      "GENERATE OTP": "HASILKAN OTP",
      "(ONE TIME PASSWORD)": "(PASSWORD SATU KALI)",
      "HAVE A REFERRAL CODE?": "PUNYA KODE REFERRAL?",
      "Don’t Have an account yet? Sign Up": "Belum punya akun? Mendaftar",
      "ProZigzagBus": "ProZigzagBusbus",
      "Date": "Tanggal",
      "Today": "Hari ini",
      "From": "Dari",
      "To": "Ke",
      "to": "ke",
      "Faq List": "Daftar FAQ",
      "Refer a Friend": "Menunjuk teman",
      "Share the referral link with your friends": "Bagikan tautan rujukan ke teman-teman Anda",
      "Logout": "Keluar",
      "Yes,Logout": "Ya, Keluar",
      "Cancel": "Membatalkan",
      "Are you sure you want to log out?": "Apakah Anda yakin ingin logout?",
      "Delete Account": "Hapus akun",
      "Yes,Remove": "Ya, Hapus",
      "Are you sure you want to delete account?": "Apakah Anda yakin ingin menghapus akun?",
      "Confirm": "Mengonfirmasi",
      "Enter Input": "Masukkan Masukan",
      "Profile Edit": "Sunting profil",
      "About": "Tentang",
      "General": "Umum",
      "My Account": "Akun saya",
      "100": "100",
      "300": "300",
      "500": "500",
      "1000": "1000",
      "1100": "1100",
      "1300": "1300",
      "1500": "1500",
      "1700": "1700",
      "2000": "2000",
      "Top up Amount": "Jumlah Isi Ulang",
      "Top up": "Isi ulang",
      "Your balance": "Keseimbanganmu",
      "Top Up": "Isi Ulang",
      "Continue": "Melanjutkan",
      "Payment Getway Methode": "Metode Jalur Pembayaran",
      "CONTINUE": "MELANJUTKAN",
      "Not Valid": "Silakan masukkan input yang valid",
      "Another Top Up": "Isi Ulang Lainnya",
      "Done For Now": "Selesai Untuk Saat Ini",
      "Successfuly": "Berhasil",
      "Transaction History": "sejarah transaksi",
      "My Wallet": "Dompetku",
      "Image saved in gallery": "Gambar disimpan di galeri",
      "Total Price": "Total harga",
      "Wallet": "Dompet",
      "Discount": "Diskon",
      "Price": "Harga",
      "Price Details": "Detail Harga",
      "Email": "Surel",
      "Full Name": "Nama lengkap",
      "Contact Details": "Detail Kontak",
      "Seat": "Kursi",
      "Age": "Usia",
      "Name": "Nama",
      "Passenger(S)": "Penumpang",
      "Ticket Id": "ID Tiket",
      "Transaction Id": "ID transaksi",
      "Payment Methode": "Metode Pembayaran",
      "Booking Date": "Tanggal Pemesanan",
      "Bus Details": "Detail Bus",
      "Completed": "Lengkap",
      "Rating": "Peringkat",
      "Enter your Feedback": "Masukkan Masukan Anda",
      "Download Ticket": "Unduh Tiket",
      "You dont`t have any booking records!": "Anda tidak memiliki catatan pemesanan apa pun!",
      "No booking found": "Tidak ada pemesanan yang ditemukan",
      "Completed Trips": "Perjalanan Selesai",
      "Upcoming Trips": "Perjalanan Mendatang",
      "My Tickets": "Tiket Saya",
      "Tax": "Pajak",
      "Pay from Wallet": "Bayar dari Dompet",
      "Remove": "Menghapus",
      "Coupon Applied !": "Kupon Berlaku!",
      "Apply Coupon": "Terapkan Kupon",
      "Apply": "Menerapkan",
      "Not Apply": "Tidak Berlaku",
      "Min Amount": "Jumlah Minimal",
      "Valid untill": "Berlaku sampai",
      "Total Pay": "Jumlah Bayaran",
      "EXTERNAL_WALLET IS": "EXTERNAL_WALLET ADALAH",
      "ERROR HERE": "KESALAHAN DI SINI",
      "SUCCESS PAYMENT": "PEMBAYARAN SUKSES",
      "gender": "jenis kelamin",
      "seat_no": "kursi_tidak",
      "age": "usia",
      "name": "nama",
      "Back to Home": "Kembali ke rumah",
      "View Transaction": "Lihat Transaksi",
      "Congratulation! your bus ticket is confirmed. For more details check the My Booking tab.": "Selamat! tiket bus Anda dikonfirmasi. Untuk lebih jelasnya periksa tab Tiket Saya.",
      "Booking Confirmed!": "Pemesanan Dikonfirmasi!",
      "Enter Age": "Masukkan Usia",
      "Enter Full Name": "Masukkan Nama Lengkap",
      "Business Email": "Email Bisnis",
      "Business Address": "Alamat bisnis",
      "Business Name": "Nama Bisnis",
      "GSTIN": "GSTIN",
      "Enter Mobile Number": "Masukkan Nomor Ponsel",
      "Enter Email id": "Masukkan ID email",
      "Email Id": "nomor email",
      "Gender": "Jenis kelamin",
      "Passenger": "Penumpang",
      "Passenger Details": "Detail Penumpang",
      "Enter Plese Input": "Masukkan Silakan Masukan",
      "(Exclusive of Taxes)": "(Tidak Termasuk Pajak)",
      "Amount :": "Jumlah :",
      "Next Step": "Langkah berikutnya",
      "Plese Select Boarding And Drop Point": "Silakan pilih Boarding dan Drop Point",
      "Droping Point": "Titik Jatuh",
      "Boarding Point": "Titik Keberangkatan",
      "Upper Berth": "Tempat Tidur Atas",
      "Lower Berth": "Tempat Tidur Bawah",
      "passengers to a single booking with this operator": "penumpang untuk satu pemesanan dengan operator ini",
      "You can not add more than": "Anda tidak dapat menambahkan lebih dari",
      "Booked by female passenger": "Dipesan oleh penumpang wanita",
      "Selected by you": "Dipilih oleh Anda",
      "Booked by Others": "Dipesan oleh Orang Lain",
      "Available": "Tersedia",
      "Know about seat types": "Ketahui tentang jenis kursi",
      "Upper Seat": "Kursi Atas",
      "Lower Seat": "Kursi Bawah",
      "Cancellation Policy": "Kebijakan Pembatalan",
      "Review": "Tinjauan",
      "Amenities": "Fasilitas",
      "Seats": "Tempat duduk",
      "/ Sleeper": "/ Tidur",
      "ProZigzagBus fulfilled buses are not available at this time.": "Bus yang dipenuhi ProZigzagBusbus tidak tersedia saat ini.",
      "Change": "Mengubah",
      "No reviews found": "Tidak ada ulasan yang ditemukan",
      "AC Seater": "Tempat Duduk AC",
      "Special Offer": "Penawaran istimewa",
      "Recent Booking": "Pemesanan Terbaru",
      "Tomorrow": "Besok",
      "not valide": "Silakan masukkan input yang valid",
      "Search Buses": "Cari Bus",
      "Enter referral code (optional)": "Masukkan kode referensi (opsional)",
      "Home": "Rumah",
      "My Ticket": "Tiket saya",
      "Account": "Akunt"
    }
  };
}